version: '2'
services :
  web :
    build: .
    command: npm run dev
    restart: always
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3001:3000"
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:changeme@postgres/tododb
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
       - ~/data/postgres:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: tododb
      PGDATA: /data/postgres
  adminer:
    image: adminer
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8080:8080